from fastapi import FastAPI, Query
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils import embedding_functions

app = FastAPI(title="Semantic Movie Search API")

MODEL_NAME = "all-MiniLM-L6-v2"
model = SentenceTransformer(MODEL_NAME)

# Connect to the persistent storage generated by load_csv.py
chroma_client = chromadb.PersistentClient(path="./chroma_storage")
embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(model_name=MODEL_NAME)
collection = chroma_client.get_or_create_collection(name="movies", embedding_function=embedding_fn)

@app.get("/search")
async def search_movies(query: str = Query(..., description="The semantic search query"), limit: int = 5):
    # Query ChromaDB. It automatically uses the metadata fields we uploaded.
    results = collection.query(
        query_texts=[query],
        n_results=limit
    )

    formatted_results = []
    if results and results['ids'] and len(results['ids'][0]) > 0:
        for i in range(len(results['ids'][0])):
            formatted_results.append({
                "id": results['ids'][0][i],
                "title": results['metadatas'][0][i]['title'],
                "director": results['metadatas'][0][i]['director'],
                "release_date": results['metadatas'][0][i]['release_date'],
                "score_rating": results['metadatas'][0][i]['vote_average'],
                "distance": results['distances'][0][i], # Closer to 0 means a closer semantic match
                # The 'document' contains the composite semantic profile we generated
                "matched_context": results['documents'][0][i]
            })

    return {
        "query": query,
        "total_results_returned": len(formatted_results),
        "results": formatted_results
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
